apiVersion: v1
kind: Secret

metadata:
  name: employee-secret
  namespace: employee-system

type: Opaque

stringData:
  DB_USERNAME: employee_user
  DB_PASSWORD: Emp@123456
  MYSQL_ROOT_PASSWORD: Root@123456
