apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: employee-pvc
  namespace: employee-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 2Gi
